/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class cn_com_lasong_media_Muxer */

#ifndef _Included_cn_com_lasong_media_Muxer
#define _Included_cn_com_lasong_media_Muxer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     cn_com_lasong_media_Muxer
 * Method:    remux
 * Signature: (Ljava/lang/String;Ljava/lang/String;DDZZ)I
 */
JNIEXPORT jint JNICALL Java_cn_com_lasong_media_Muxer_remux
        (JNIEnv *, jobject, jstring, jstring, jdouble, jdouble, jboolean, jboolean);

#ifdef __cplusplus
}
#endif
#endif
