/* DO NOT EDIT THIS FILE - it is machine generated */
/* Header for class net_sourceforge_resample_Resample */
#include <jni.h>
#ifndef _Included_cn_com_lasong_media_Resample
#define _Included_cn_com_lasong_media_Resample
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     cn_com_lasong_media_Resample
 * Method:    mix
 * Signature: (Ljava/nio/ByteBuffer;[B)V
 */
JNIEXPORT void JNICALL Java_cn_com_lasong_media_Resample_mix
        (JNIEnv *, jclass, jobject, jbyteArray);

/*
 * Class:     cn_com_lasong_media_Resample
 * Method:    resample
 * Signature: (J[BI)I
 */
JNIEXPORT jint JNICALL Java_cn_com_lasong_media_Resample_resample
        (JNIEnv *, jobject, jlong, jbyteArray, jint);

/*
 * Class:     cn_com_lasong_media_Resample
 * Method:    read
 * Signature: (J[BI)I
 */
JNIEXPORT jint JNICALL Java_cn_com_lasong_media_Resample_read
        (JNIEnv *, jobject, jlong, jbyteArray, jint);

/*
 * Class:     cn_com_lasong_media_Resample
 * Method:    init
 * Signature: (JJIIJIILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_cn_com_lasong_media_Resample_init
        (JNIEnv *, jobject, jlong, jlong, jint, jint, jlong, jint, jint);
/*
 * Class:     cn_com_lasong_media_Resample
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_cn_com_lasong_media_Resample_destroy
        (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
